# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Uncomment to disable checks of spelling mistakes

# --------------------------------------------------------------------------------------------------------------
# Suppress fun output cause I'm boring
PRINT_ALPACA: false

# Flag to clear files from report folder (usually megalinter-reports) before starting the linting process
CLEAR_REPORT_FOLDER: true

#DISABLE_LINTERS:
#  - C_CLANG_FORMAT-ERROR
#  - CPP_CLANG_FORMAT-ERROR

CPP_CPPLINT_ARGUMENTS: "--filter=-whitespace"
C_CPPLINT_ARGUMENTS: "--filter=-whitespace"

# only look in the code/ directory (but this assumes you downloaded mega-linter in the repository
FILTER_REGEX_INCLUDE: (code/)

# How much output the script will generate to the console: INFO (default), DEBUG, WARNING or ERROR. 
LOG_LEVEL: INFO #ERROR 

# in theory to move the mega-linter folder
#REPORT_OUTPUT_FOLDER: ../${GITHUB_WORKSPACE}/megalinter-reports

# ---------------------------------------------------------------------------------------------------------------

SHOW_ELAPSED_TIME: true

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
