[project]
name = "supercode"
version = "0.2.0"
license = "Apache-2.0"
readme = "README.md"
authors = [
  {name = "Elisa Chiarotto"},
]
description = "SuperCode model package"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.14.0",
    "bitsandbytes>=0.50.2",
    "datasets>=5.0.1",
    "faiss-cpu>=1.15.1",
    "gemlite>=0.5.1.post1",
    "gptqmodel>=7.5.0",
    "huggingface-hub>=1.32.0",
    "human-eval>=1.0.3",
    "intel-extension-for-pytorch>=2.8.0",
    "langchain>=1.4.1",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langchain-text-splitters>=1.1.2",
    "llama-cpp-python>=0.3.35",
    "llmcompressor>=0.13.0",
    "lm-eval>=0.4.13",
    "matplotlib>=3.11.2",
    "numpy>=2.2.6",
    "optimum>=2.3.0",
    "pip>=26.2.1",
    "pyyaml>=6.0.3",
    "sentence-transformers>=6.0.1",
    "sentencepiece>=0.2.2",
    "sinq>=0.2.0",
    "tiktoken>=0.14.0",
    "torch>=2.13.0",
    "transformers>=5.14.1",
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
run-supercode = "supercode.__main__:main"
