---
# general
backend: llama_cpp # valid values: ["transformers", "llama_cpp", #"vLLM"]
verbose: 0 # how much info is printed: 0=none, 1=little, 2=lots, 3=all

model_iter: 1 # n of times the model loops over the same issue (1 = run only once), recommended setting is 1
tools_iter: 0 # n steps for choosing tools (0 = no tools, 1 = all tools in one go), recommended setting is 2-3

# ---------------------------------------------------------------------------------------------------------------------
# NOTE: the model can be loaded as quantized only if someone published the quantized version (see file's extensions):
# full precision, based on:
#     - model.safetensors
#     - pytorch_model.bin.index.json (NOT compatible with Transformers!)
# on-the-fly quantization, based on:
#     - model-4bit.safetensors (needs bitsandbytes, sinq, HQQ or torchao)
# calibration-based quantization (direct load), based on:
#     - model.safetensors (AWQ)
#     - gptq_model-4bit-128g.safetensors
#     - model.gguf (NOT compatible with Transformers!)

# coder assistant
coder_model:
    model_id: # model ID from HuggingFace, size for Qwen2.5: 32B, 14B, 7B, 3B, 1.5B, 0.5B,
        # file size (for 1.5B) is: GPTQ-Int4 (1.16 GB) ~ AWQ (1.63 GB) < full (3.1 GB) < GGUF (9.76 GB)
        # --------------------------------------------------------------------------------------------
        #Qwen/Qwen2.5-Coder-3B-Instruct
        #Qwen/Qwen3-4B
        #Qwen/Qwen3-Coder-Next # MoE, 3B active and 80B total
        #codellama/CodeLlama-7b-Instruct-hf
        #google/codegemma-7b-it

        # --------------------------------------------------------------------------------------------
        #Qwen/Qwen2.5-Coder-1.5B-Instruct
        #Qwen/Qwen2.5-Coder-1.5B-Instruct-GPTQ-Int4
        #Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ
        Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF

        #mradermacher/hpc-coder-v2-6.7b-GGUF # HPC-coder, fine-tuned version of Deepseek Coder 6.7b

    quant_type: pretrained # valid values: ["pretrained", "gguf", "compressor", "bits", "sinq"] --> check file formats!!!
    # SINQ doesn't work!!! prequantized AWQ and GPTQ models can be loaded using pretrained
    gen_mode: multisample # valid values: ["multisample", "stream"]
    # either pass the arguments for multi-sampling or enable streaming (show the tokens as they are generated)

    gen_args: # I'm using parameter names from transformers. NOTE: parameters are called differently in llama.cpp
        temperature: 0.8 # 0 = always select the most likely word; 1 = unmodified logit distribution; >1 = more and more random
        max_new_tokens: 6000 # max number of tokens that can be generated
        # Note: max_length = max total tokens (incl input and output), but it is going to be deprecated soon
        #top-p: 0.9 # this is a confidence-adaptive filter: threshold based on the CUMULATIVE prob of the tokens
        #presence_penalty: 0.3 # positive values penalize repeating sentences and words (range [-2,+2], advisable to keep in [-1,+1] for good performances)
        #frequency_penalty: 0.2 # high to avoid repetition of specific words (presence is more about having new topics)
        # Reminder that code from LLMs has been shown to be more repetitive than human's, so it makes sense to penalize it a bit!

    multi_sampl_args: # not supported in llama.cpp
        num_return_sequences: 5 # n of samples per input
        do_sample: True,  # enable sampling for diversity, default is false to use greedy decoder
        num_beams: 5 # explore multiple sequences in parallel (then select the top ones), must be larger or equal to num_return_sequences
        early_stopping: True # stop when all beams have finished
        no_repeat_ngram_size: 2 # avoid repeating n-grams


# thinking model for choosing tools (good at extrapolating logic issues)
think_model:
    model_id: # model ID from HuggingFace
        Qwen/Qwen3-0.6B # includes thinking mode by default
        #Qwen/Qwen3-0.6B-GGUF # includes thinking mode by default

        #Qwen/Qwen3-4B # includes thinking mode by default
        #Qwen/Qwen3-4B-Thinking-2507
        #Qwen/Qwen3.5-4B # DOESN'T WORK??? # includes thinking mode by default
    quant_type: pretrained
    gen_mode: stream
    gen_args:
        temperature: 0.4 # 0 = always select the most likely word, 1 = random
        max_new_tokens: 6000 # max number of tokens that can be generated
        #top-p: 0.9 # this is a confidence-adaptive filter: threshold based on the CUMULATIVE prob of the tokens
        presence_penalty: 1.0 # positive values penalize repeating sentences and words (range [-2,+2], advisable to keep in [-1,+1] for good performances)
        frequency_penalty: 0.2 # high to avoid repetition of specific words (presence is more about having new topics)

# ---------------------------------------------------------------------------------------------------------------------
# embedding model for building the database (for RAG)
emb_model_id: sentence-transformers/msmarco-bert-base-dot-v5  # model ID from HuggingFace

# folders
tools_dir:     tools-outputs # where I save the results from the agent's tools
docs_dir:      RAG-codebase # where I save the files for RAG
db_dir:        src/database/code-db  # where I save the vector database (db) for RAG
docker_dir:    src/docker_env # where I save the dockerfile and docker_compose.yml
gen_code_dir:  src/docker_env/results # where I mount with the docker container
gen_code_file: src/docker_env/results/gen_code/gen_code_temp.py # where I save the temp file for generating code

# database (RAG)
chunk_size: 1000
chunk_overlap: 200
update_db: false # if I want to update the db (for example because I changed some files)
