# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE  # Uncomment to disable checks of excessive copy-pastes
  - SPELL      # Uncomment to disable checks of spelling mistakes
  - REPOSITORY # Uncomment to disable all git checks (ex: if files are not in a repository)

# --------------------------------------------------------------------------------------------------------------
# Suppress fun output cause I'm boring
PRINT_ALPACA: false

# How much output the script will generate to the console: INFO (default), DEBUG, WARNING or ERROR.
LOG_LEVEL: INFO

# whether to print general info
SHOW_ELAPSED_TIME: true # display elapsed time in reports
PRINT_ALL_FILES: true # display all files analyzed by the linters instead of only the number.

# Flag to clear files from report folder (usually megalinter-reports) before starting the linting process
CLEAR_REPORT_FOLDER: true
VALIDATE_ALL_CODEBASE: true # when set to false, only new or edited files will be parsed for validation.

# in theory to move the mega-linter folder, but it doesn't work :(
#REPORT_OUTPUT_FOLDER: "../tool-outputs/megalinter-reports/"

# The location containing files to lint if you are running locally.
DEFAULT_WORKSPACE: /RAG-codebase

# only look in the directory (but this assumes you downloaded mega-linter in the repository!)
FILTER_REGEX_INCLUDE: (../RAG-codebase/) #(../src/docker_env/results/gen_code/) #

# ignore following files
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.venv|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'

#CPP_ARGUMENTS: "--filter=-whitespace"
#CPP/C_CPPLINT_ARGUMENTS: "--filter=-whitespace"

# whether to print the reports on terminal
#CONSOLE_REPORTER: false
#MARKDOWN_SUMMARY_REPORTER: false
#GITHUB_STATUS_REPORTER: false
#EMAIL_REPORTER: false
#FILEIO_REPORTER: false
#JSON_REPORTER: false
#SARIF_REPORTER: false

#DISABLE_LINTERS:
#  - C_CLANG_FORMAT-ERROR
#  - CPP_CLANG_FORMAT-ERROR

# ---------------------------------------------------------------------------------------------------------------

SECURITY_SUGGESTIONS: false

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
