print("start...")
import numpy as np
import subprocess, os
import ast
import tempfile

from human_eval.data import write_jsonl, read_problems
from datasets import load_dataset # load datasets from Hugging Face
#from src.configs.parse_config import *

#print("current dir:", os. getcwd())

verbose = 0

def sandboxed_compiler(function, test=None, entry_point=None):
    if verbose>0 : print(">> using the sandboxed_compiler")
    # this only checks if the code compiles (semantic correctness)
    """
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as tmp:
        print("create temp file")
        tmp.write(function)
        tmp_path = tmp.name
    """
    # IMPORTANT: the docker image can see ONLY files inside "results/"
    # and all paths in the container should be relative to "results/"!

    docker_dir = "src/docker_env"  # where I save the dockerfile and docker_compose.yml
    gen_code_file = docker_dir+"/results/gen_code/gen_code_temp.py"  # where I mount with the docker container

    cwd = os.getcwd() #; print(cwd)
    abs_docker_path = cwd+"/"+docker_dir
    #tmp_dir = abs_docker_path+"/results/gen_code"

    if test == None: code = function
    else: code = function+"\n\n"+test+"\n\ncheck("+entry_point+")" # issue: this would work only for HumanEval!

    with open(gen_code_file, "w") as f:
        if verbose>1 : print(">> saving the code at", gen_code_file)
        f.write(code)
        f.close()
    try:
        docker_code_path = gen_code_file[gen_code_file.find("results/"):]
        if verbose>1 : print(">> docker_code_path", docker_code_path)
        if verbose>1 : print(">> run command with docker run")
        #subprocess.run("pwd")
        # docker run --rm sandbox_code python3 results/gen_code/gen_code_temp.py
        # docker run --mount type=bind,src=/home/elisa/PycharmProjects/phd-leiden-supercode/supercode/src/docker_env/results,dst=/workspace --rm sandbox_code
        result = subprocess.run( # run a program from inside the container (and remove the container afterwards)
            ["docker", "run", "--mount", "type=bind,src="+abs_docker_path+",dst=/workspace", "--rm", "sandbox_code", "python3", docker_code_path],
            capture_output=True,
            text=True,
            timeout=10 # seconds
        )
        if verbose>1 : print(">> command run successfully\n", result)
        return result.returncode, "printed_output='" + result.stdout + "'\nerrors='" + result.stderr + "'"
    except Exception as e:
        print("Error in sandboxed_compiler tool:", e)
        return 1, "Error in sandboxed_compiler tool:"+str(e)

# paths
bench_name = "humaneval"
num_samples_per_task=5 ; iter = "" #"_x3"
model_name = "Qwen3-4B" # "Qwen3-Coder-Next" # "Qwen2.5-Coder-3B-Instruct" # "Qwen2.5-Coder-3B-Instruct+Qwen3-4B" #
gen_code_dir = "src/docker_env/results" # where I save the code generated by the agent, so it can be tested

#base_file_name  = bench_name+"_baseline-" +model_name+"_"+str(num_samples_per_task)#"1+4"#
#bench_file_name = bench_name+"_benchmark-"+model_name+"_"+str(num_samples_per_task)#"1+4"#
base_file_name  = gen_code_dir+"/"+bench_name+"_"+model_name+"_baseline_" +str(num_samples_per_task)+iter+".jsonl"
bench_file_name = gen_code_dir+"/"+bench_name+"_"+model_name+"_benchmark_"+str(num_samples_per_task)+iter+".jsonl"

# importing the benchmark from hugging face
if verbose>0 : print("loading benchmark...")
dataset = load_dataset("openai/openai_humaneval")
if verbose>0 : print("reading the problems...")
problems = read_problems()

performance_plot_vals = []
performance_plot_stds = []

for file_name in [base_file_name, bench_file_name]:
    # initializing vars
    comp_pass = [ 0 for i in range(num_samples_per_task) ]
    comp_fail = [ 0 for i in range(num_samples_per_task) ]
    test_pass = [ 0 for i in range(num_samples_per_task) ]
    test_fail = [ 0 for i in range(num_samples_per_task) ]
    samples = []

    print("\n-----------------------------------------------------------------\nEvaluating: "+file_name)
    with open(file_name) as f:
        for i, line in enumerate(f, start=1):
            try:
                samples.append(ast.literal_eval(line))
            except Exception as e:
                print("Error on line", i)
                print("Line content:", repr(line))
                raise

    for i, sample in enumerate(samples):
        if verbose>1 : print("\n------------------------------------------------------------\n### sample:", sample["task_id"])
        task_id = sample["task_id"]
        function = sample["code"] #; print("code: \n```\n", function, "\n```\n", sep='')
        entry_point = problems[task_id]["entry_point"] # name of the function
        test = problems[task_id]["test"]
        j = i % num_samples_per_task # for calculating the variance

        # check just the code
        returncode, output = sandboxed_compiler(function)
        if verbose>2 : print("compiler: returncode = ", returncode, "\n", output, sep='')
        if returncode==0: comp_pass[j]+=1
        else: comp_fail[j]+=1

        # check with test cases
        returncode, output = sandboxed_compiler(function, test, entry_point)
        if verbose>2 : print("test: returncode = ", returncode, "\n", output, sep='')
        if returncode==0: test_pass[j]+=1
        else: test_fail[j]+=1

    comp_pass_tot = sum(comp_pass) ; comp_pass_std = np.var(comp_pass)
    comp_fail_tot = sum(comp_fail) ; comp_fail_std = np.var(comp_fail)
    test_pass_tot = sum(test_pass) ; test_pass_std = np.var(test_pass)
    test_fail_tot = sum(test_fail) ; test_fail_std = np.var(test_fail)
    tot_samples = len(samples)

    # final summary
    print("===========================================")
    print(f"compiler pass:\t{comp_pass_tot}\t({comp_pass_tot/tot_samples*100:.2f}% +/- {comp_pass_std/tot_samples*100:.2f}%)\t{comp_pass}")
    print(f"compiler fail:\t{comp_fail_tot}\t({comp_fail_tot/tot_samples*100:.2f}% +/- {comp_fail_std/tot_samples*100:.2f}%)\t{comp_fail}")
    print("-------------------------------------------")
    print(f"test pass:   \t{test_pass_tot}\t({test_pass_tot/tot_samples*100:.2f}% +/- {test_pass_std/tot_samples*100:.2f}%)\t{test_pass}")
    print(f"test fail:   \t{test_fail_tot}\t({test_fail_tot/tot_samples*100:.2f}% +/- {test_fail_std/tot_samples*100:.2f}%)\t{test_fail}")
    print("-------------------------------------------")
    print(f"Total samples:\t{tot_samples}")
    print("===========================================")

    # for the plot: baseline(ex, test) + bench(ex, test), variance
    performance_plot_vals.extend([
        round(comp_pass_tot/tot_samples*100, 2),
        round(test_pass_tot/tot_samples*100, 2)
    ])
    performance_plot_stds.extend([
        round(comp_pass_std/tot_samples*100, 2),
        round(test_pass_std/tot_samples*100, 2)
    ])

print(f"vals & stds: \n{performance_plot_vals},\n{performance_plot_stds}\n")
"""
import json

samples = []
with open("humaneval_baseline.jsonl") as f:
    for i, line in enumerate(f, start=1):
        try:
            obj = json.loads(line)
        except Exception as e:
            print("Error on line", i)
            print("Line content:", repr(line))
            raise

for sample in samples:
    print("\n\n### sample:", sample["task_id"])
    function = sample["completion"]
    try: subprocess.run(["python from typing import List \n"+function], shell=True)
    except Exception as e: print(e)
"""